config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :meetings, only: [:create, :show] do
    resources :reviews, only: [:new, :create]
    get 'review'
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :reviews

  before_create :set_slugs

  def review_results
    return {} if reviews.empty?
    {
      agenda: {
        true: true_results(:agenda),
        false: false_results(:agenda)
      },
      agenda_met: avg(:agenda_met),
      appropriate_meeting_time: avg(:appropriate_meeting_time),
      appropriate_meeting_length: avg(:appropriate_meeting_length),
      started_on_time: avg(:started_on_time),
      ended_on_time: avg(:ended_on_time),
      action_items: {
        true: true_results(:action_items),
        false: false_results(:action_items)
      },
      on_topic: avg(:on_topic),
      usefulness: avg(:usefulness),
      necessary_to_attend: avg(:necessary_to_attend),
      ability_to_contribute: avg(:ability_to_contribute)
    }
  end

  private
  def avg(attribute)
    (reviews.map{|r| r.send(attribute)}.reduce(:+) / reviews.count.to_f).round(1)
  end

  def true_results(attribute)
    ((reviews.map{|r| r.send(attribute)}.count(true) / reviews.count.to_f) * 100).round(1)
  end

  def false_results(attribute)
    ((reviews.map{|r| r.send(attribute)}.count(false) / reviews.count.to_f) * 100).round(1)
  end

  def set_slugs
    loop do
      self.share_slug = SecureRandom.hex(10)
      self.review_slug = SecureRandom.hex(10)
      break unless Meeting.where(share_slug: share_slug).exists? || Meeting.where(review_slug: review_slug).exists?
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :meeting
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      flash[:notice] = "Your review for meeting `#{@meeting.title}` has been created."
      redirect_to meeting_url(@meeting.review_slug)
    else
      flash[:error] = "We could not create a meeting review, please try again"
      redirect_to :root
    end
  end

  def show
    @meeting = Meeting.find_by(review_slug: params[:id])
  end

  def review
    @meeting = Meeting.find_by(review_slug: params[:meeting_id])
    @results = @meeting.review_results
  end

  private
  def meeting_params
    params.require(:meeting).permit(:title)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_meeting, only: [:new, :create]

  def new
    @review = Review.new(meeting: @meeting)
  end

  def create
    @review = Review.new(review_params)

    if @review.save
      flash[:notice] = "Thank you for reviewing `#{@review.meeting.title}`. Your review has been successfully submitted to the organizer."
      redirect_to :root
    else
      flash[:error] = @review.errors.full_messages
      render :new
    end
  end

  private
  def set_meeting
    @meeting = Meeting.find_by(share_slug: params[:meeting_id])
  end

  def review_params
    params.require(:review).permit(
      :agenda,
      :agenda_met,
      :appropriate_meeting_time,
      :appropriate_meeting_length,
      :started_on_time,
      :ended_on_time,
      :action_items,
      :on_topic,
      :usefulness,
      :necessary_to_attend,
      :ability_to_contribute,
      :improvements,
      :other_comments
    ).merge(meeting: @meeting)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<h2 class="font-bold mb-2">Was your last meeting totally useless?</h2>
<p class="mb-4">
  Find out! Create an anonymous feedback form to send out to your meeting invitees to see what they think.
</p>
<p class="mb-4">
  The survey is completely anonymous and the results are aggregated and randomized to maintain the privacy of your meeting attendees.
</p>
<h4>How do I get started?</h4>
<p class="mb-4">
  Its simple! You create a new Meeting Review that will generate a randomized, untrackable URL that you can then send out to your meeting attendees. The attendees will then fill out a quick 2 minute survey and submit the results. You can then go to the Meeting Review Results page to see how you did. Simple as that.
</p>

<%= form_with scope: :meeting, url: meetings_path, local: true do |form| %>
  <p>
    <%= form.label 'Simply type the name of a meeting you would like to review' %>
    <%= form.text_field :title, placeholder: "Ex: Sprint Acceptance Demo (Monday @ 8am)" %>
  </p>
  <p class="mt-2 mb-4">
    <%= form.submit 'Start a Meeting Review' %>
  </p>
<% end %>

<h4>What kind of questions does the survey ask?</h4>
<p class="text-gray-700 text-base mb-4">
  The survey asks the following 13 simple questions:
  <ul class="text-gray-700 list-disc ml-8">
    <li>Was the meeting accompanied by an agenda?</li>
    <li>Was the agenda met?</li>
    <li>Did the meeting take place at an appropriate time of day?</li>
    <li>Was the meeting the appropriate length for the agenda?</li>
    <li>Did the meeting start on time?</li>
    <li>Did the meeting end on time?</li>
    <li>Did the meeting generate good action items?</li>
    <li>Did the meeting stay on topic?</li>
    <li>Did you find use in this meeting?</li>
    <li>Did you feel that it was necessary that you were in attendance?</li>
    <li>Did you feel like you were free to contribute to the conversation?</li>
    <li>How would you improve this meeting?</li>
    <li>Anything else you would like to tell the meeting organizer?</li>
  </ul>
</p>

app/views/layouts/_notice.html.erb
<div class="bg-blue-100 border border-blue-500 text-blue-700 px-4 py-3 mt-4 mb-4" role="alert">
  <p class="font-bold">Notice:</p>
  <p class="text-sm"><%= message %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UselessMeeting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body class="text-gray-700 leading-normal mt-24 mb-24">
    <div class="w-full max-w-screen-xl mx-auto px-6">
      <% if flash[:notice] %>
        <%= render partial: 'layouts/notice', locals: { message: flash[:notice] } %>
      <% end %>

      <% if flash[:error] %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 mb-4 rounded relative" role="alert">
          <strong class="font-bold">Holy smokes!</strong>
          <span class="block sm:inline"><%= flash[:error] %></span>
        </div>
      <% end %>
      <div class="max-w-full rounded overflow-hidden shadow-lg">
        <div class="px-6 py-4">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/meetings/_boolean.html.erb
<div class="mt-2 mb-2 clearfix">
  <h5><%= title %></h5>
  <% unless data.blank? %>
    <% unless data[:false].zero? %>
      <div style="width: <%= data[:false] %>%" class="float-left bg-red-200 text-center">False (<%= data[:false] %>%)</div>
    <% end %>
    <% unless data[:true].zero? %>
      <div style="width: <%= data[:true] %>%" class="float-left bg-green-200 text-center">True (<%= data[:true] %>%)</div>
    <% end %>
  <% end %>
</div>

app/views/meetings/_center_range.html.erb
<div class="mt-2 mb-2 clearfix">
  <h5><%= title %></h5>
  <% unless value.blank? %>
    <% color = value < 2 || value > 8 ? 'red' : (value < 4 || value > 6 ? 'orange' : 'green') %>
    <div class="bg-<%= color %>-100 border border-<%= color %>-400 text-<%= color %>-700 px-4 py-3 rounded relative" role="alert">
      <%= range_field_tag :agenda, value, in: 0..10, step: 0.1, disabled: true %>
    </div>
  <% end %>
</div>

app/views/meetings/_range.html.erb
<div class="mt-4 mb-2 clearfix">
  <div class="my-2 clearfix">
    <h5 class="float-left"><%= title %><h5>
    <span class="float-right rounded-full bg-gray-200 uppercase px-2 py-1 text-xs font-bold mr-3"><%= value %></span>
  </div>
  <% unless value.blank? %>
    <% color = value > 4 ? (value > 8 ? 'green' : 'orange') : 'red' %>
    <div class="bg-<%= color %>-100 border border-<%= color %>-400 text-<%= color %>-700 px-4 py-3 rounded relative" role="alert">
      <%= range_field_tag :agenda, value, in: 0..10, step: 0.1, disabled: true %>
    </div>
  <% end %>
</div>

app/views/meetings/review.html.erb
<h2 class="font-bold mb-2"><%= @meeting.title %></h2>
<div class="clearfix">
  <%= link_to "< Meeting Share Link", meeting_path(@meeting.review_slug), class: 'float-left' %>
  <% unless @meeting.reviews.count.zero? %>
    <div class="float-right align-middle">
      Results based off
      <span class="rounded-full bg-gray-200 uppercase px-2 py-1 text-xs font-bold"><%= @meeting.reviews.count %></span>
      responses
    </div>
  <% end %>
</div>
<h3 class="mt-4">
  Your meeting score:
</h3>
<% if @results.blank? %>
  <%= render partial: 'layouts/notice', locals: { message: "There currently isn't any data. Please either bookmark this page and come back at a later time or refresh this page after all responses have be received." } %>
<% else %>
  <p>
    <%= render partial: 'boolean', locals: {title: 'Agenda?', data: @results[:agenda]} %>
    <%= render partial: 'boolean', locals: {title: 'Action items?', data: @results[:action_items]} %>

    <%= render partial: 'range', locals: {title: 'Agenda Met Average Score', value: @results[:agenda_met]} %>
    <%= render partial: 'range', locals: {title: 'Appropriate Meeting Time Average Score', value: @results[:appropriate_meeting_time]} %>
    <%= render partial: 'range', locals: {title: 'Appropriate Meeting Length Average Score', value: @results[:appropriate_meeting_length]} %>
    <%= render partial: 'range', locals: {title: 'Start Time Average Score', value: @results[:started_on_time]} %>
    <%= render partial: 'range', locals: {title: 'End Time Average Score', value: @results[:ended_on_time]} %>
    <%= render partial: 'range', locals: {title: 'On Topic Average Score', value: @results[:on_topic]} %>
    <%= render partial: 'range', locals: {title: 'Usefulness Average Score', value: @results[:usefulness]} %>
    <%= render partial: 'range', locals: {title: 'Necessity Average Score', value: @results[:necessary_to_attend]} %>
    <%= render partial: 'range', locals: {title: 'Contribution Average Score', value: @results[:ability_to_contribute]} %>
  </p>
  <h3>Improvement Recommendations:</h3>
  <% if @meeting.reviews.map(&:improvements).reject(&:blank?).count.zero? %>
    <%= render partial: 'layouts/notice', locals: { message: "Nobody has left any Meeting Improvement Recommendations yet" } %>
  <% else %>
    <% @meeting.reviews.map(&:improvements).shuffle.reject(&:blank?).each do |improvement| %>
      <p class="text-gray-700 bg-gray-100 text-base mt-4 p-4">
        <%= improvement %>
      </p>
    <% end %>
  <% end %>
  <h3>Other Comments:</h3>
  <% if @meeting.reviews.map(&:other_comments).reject(&:blank?).count.zero? %>
    <%= render partial: 'layouts/notice', locals: { message: "Nobody has left any Other Comments about your Meeting yet" } %>
  <% else %>
    <% @meeting.reviews.map(&:other_comments).shuffle.reject(&:blank?).each do |comment| %>
      <p class="text-gray-700 bg-gray-100 text-base mt-4 p-4">
        <%= comment %>
      </p>
    <% end %>
  <% end %>
<% end %>

app/views/meetings/show.html.erb
<h2 class="font-bold mb-2"><%= @meeting.title %></h2>
<p class="text-gray-700 text-base mt-4">
  <label>Copy and paste this share URL with your team:</label>
  <input type="text" disabled value=<%= new_meeting_review_url(@meeting.share_slug) %> />
</p>
<p class="text-gray-700 text-base mt-4">
  Once you have sent the URL out to your team, you can view an agregated and anonymized list of the results.
  <%= link_to 'View the results of your survey >', meeting_review_path(@meeting.review_slug) %>
</p>
<p class="text-gray-700 text-base mt-4">
  Please bookmark this page so you don't lose the results of this survey. We generate random URLs for you to improve the privacy of the results, if you lose the URL, you will also lose your results.
</p>

app/views/reviews/new.html.erb
<h2 class="font-bold mb-2"><%= @meeting.title %></h2>
<p class="mb-4">
  Please review this meeting. All results are completly anonymous. The data is aggregated and randomized when shown to the organizer to help protect the privacy of your feedback. Be as honest as possible.
</p>
<hr class="border border-blue-300 mt-8 mb-12" />
<%= form_with scope: :review, url: meeting_reviews_path(@meeting.share_slug), local: true do |form| %>
  <div class="mb-12">
    <%= form.check_box :agenda, class: 'float-left mt-1 mr-2' %>
    <%= form.label :agenda, 'Meeting was accompanied by an agenda' %>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Was that agenda met?' %>
    <%= form.range_field :agenda_met, in: 0..10, step: 1 %>
    <span class="float-left">No way in hell</span>
    <span class="float-right">Crushed it</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did the meeting take place at an appropriate time of day?' %>
    <%= form.range_field :appropriate_meeting_time, in: 0..10, step: 1 %>
    <span class="float-left">Way too early/late</span>
    <span class="float-right">Perfect time of day to meet</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Was the meeting the appropriate length for the agenda?' %>
    <%= form.range_field :appropriate_meeting_length, in: 0..10, step: 1 %>
    <span class="float-left">Way too little/much time</span>
    <span class="float-right">Meeting length was perfect</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did the meeting start on time?' %>
    <%= form.range_field :started_on_time, in: 0..10, step: 1 %>
    <span class="float-left">Started very late</span>
    <span class="float-right">Started on time</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did the meeting end on time?' %>
    <%= form.range_field :ended_on_time, in: 0..10, step: 1 %>
    <span class="float-left">Ran very late</span>
    <span class="float-right">Ended on time</span>
  </div>
  <div class="mb-12">
    <%= form.check_box :action_items, class: "float-left mt-1 mr-2" %>
    <%= form.label :action_items, 'Meeting generated good action items' %>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did the meeting stay on topic?' %>
    <%= form.range_field :on_topic, in: 0..10, step: 1 %>
    <span class="float-left">Nope.</span>
    <span class="float-right">Perfectly</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did you find use in this meeting?' %>
    <%= form.range_field :usefulness, in: 0..10, step: 1 %>
    <span class="float-left">Completely and utterly useless</span>
    <span class="float-right">Best thing since sliced bread</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did you feel that it was necessary that you were in attendance?' %>
    <%= form.range_field :necessary_to_attend, in: 0..10, step: 1 %>
    <span class="float-left">Why was I here???</span>
    <span class="float-right">Required.</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Did you feel like you were free to contribute to the conversation?' %>
    <%= form.range_field :ability_to_contribute, in: 0..10, step: 1 %>
    <span class="float-left">I couldn't speak my mind</span>
    <span class="float-right">Completely free</span>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'How would you improve this meeting?' %>
    <%= form.text_area :improvements %>
  </div>
  <div class="mb-12 clearfix">
    <%= form.label 'Anything else you would like to tell the meeting organizer?' %>
    <%= form.text_area :other_comments %>
  </div>
  <div class="clearfix">
    <%= form.submit 'Submit Meeting Review', class: 'float-right' %>
  </div>
<% end %>